<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.microtech</groupId>
    <artifactId>micro-loyalty</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>micro-loyalty</name>
    <description>Hệ sinh thái Khách hàng thân thiết Liên minh và Cổng Game Đa thuê bao</description>

    <modules>
        <module>src/lib/ims-libraries</module>
        <module>src/lib/loyalty-engine</module>
        <module>src/service</module>
    </modules>

</project>
