server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /loyalty-service

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: loyalty-service
  datasource:
    # Cũ: url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/loyalty_db}
    # Cũ: username: ${SPRING_DATASOURCE_USERNAME:postgres}
    # Cũ: password: ${SPRING_DATASOURCE_PASSWORD:T3st$2025}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15435}/loyalty_db}
    username: ${SPRING_DATASOURCE_USERNAME:loyalty_app}
    password: ${SPRING_DATASOURCE_PASSWORD:Loyalty_SecureDB2026!}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: LoyaltyHikariCP
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 30000
      connection-timeout: 5000
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: false
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  data:
    redis:
      # Cũ: port: ${REDIS_PORT:6380}
      # Cũ: password: ${REDIS_PASSWORD:NatCash2022}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:16385}
      password: ${REDIS_PASSWORD:Loyalty_RedisPass2026!}
      timeout: 3000ms

# Cấu hình bảo mật HMAC & Khóa Kép
loyalty:
  security:
    timestamp-drift-tolerance-seconds: 300
    master-key: ${LOYALTY_MASTER_KEY:c21hcnQtbG95YWx0eS1tYXN0ZXIta2V5LWFlczI1Ng==}
  tenant:
    default-tenant: NATCASH
    header-name: X-Tenant-Id

# Cấu hình OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

# Cấu hình Giám sát Micrometer & Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
